font:
  normal:
    family: MesloLGM Nerd Font
    style: Regular
  bold:
    family: MesloLGM Nerd Font
    style: Bold
  italic:
    family: MesloLGM Nerd Font
    style: Italic
  bold_italic:
    family: MesloLGM Nerd Font 
    style: Italic
  size: 13

window:
  decorations: none
  opacity: 0.4
  dynamic_padding: true
  startup_mode: Maximized

shell:
  program: /bin/zsh
  args:
    - --login

draw_bold_text_with_bright_colors: true

colors:
  # Default colors
  primary:
    background: '#10100E'
    foreground: '#C6C6C4'

  # Normal colors
  normal:
    black: '#10100E'
    red: '#C40233'
    green: '#009F6B'
    yellow: '#FFD700'
    blue: '#0087BD'
    magenta: '#9A4EAE'
    cyan: '#20B2AA'
    white: '#C6C6C4'

  # Bright colors
  bright:
    black: '#696969'
    red: '#FF2400'
    green: '#03C03C'
    yellow: '#FDFF00'
    blue: '#007FFF'
    magenta: '#FF1493'
    cyan: '#00CCCC'
    white: '#FFFAFA'
theme: Blood-Moon
